### ISSUE TITLE
Fail to build with protoc 3.1.0

### ISSUE THREAD

**Issue by tobegit3hub** [cmars/tfclient#2]
Now I clone the project in my $GOPATH and try to build. It fails and the error log looks like this.

```
➜  tfclient git:(master) go build
# github.com/cmars/tfclient/vendor/tensorflow_serving/apis
vendor/tensorflow_serving/apis/prediction_service.pb.go:27: undefined: grpc.SupportPackageIsVersion3
```

And the version of `protoc` is 3.1.0 which should support protobuf 3.

```
➜  tfclient git:(master) protoc --version
libprotoc 3.1.0
```

I can `go build` if I comment out that line of code. But I'm still confused about how to run this. Do you mind adding more introduction about compiling and usage?

**Comment by radekdymacz** [comment]
+1

**Comment by cmars** [comment]
Ok, ok, I'll try to look at this soon! :) In my haste, I lost the commands I used to create the protobuf shims, so this will be a fun rediscovery process..

**Comment by ilaripih** [comment]
I compiled the latest .proto files with protoc 3.1.0 and created a fork in case someone's interested: https://github.com/ilaripih/tfclient

**Comment by cmars** [comment]
Merged. Thanks @ilaripih !
